# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# set work directory
WORKDIR /app

# install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# install python dependencies
COPY pyproject.toml .
COPY uv.lock .
COPY README.md .
COPY memory_mcp ./memory_mcp
COPY tests ./tests

RUN pip install --upgrade pip \
    && pip install .

# expose port if necessary (optional)
# EXPOSE 8000

# command to run the server
ENTRYPOINT ["memory-mcp"]
